# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectExample

end

target 'MantisConnectKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MantisConnectKit
  pod 'Alamofire'

  target 'MantisConnectKitTests' do
    # Pods for testing
  end

end
